dist: trusty
git:
    submodules: false
language: python
python:
    - "3.5"
install:
    - "deactivate"  # Get out of virtualenv
    - "travis_wait 30 make setup PYTHON=/opt/python/3.5/bin/python"
script: "travis_wait 30 make test"
