dist: trusty
git:
    submodules: false
language: python
python:
    - "3.5"
install:
    - "deactivate"  # Get out of virtualenv
    - "travis_wait 30 make setup PYTHON=/opt/python/3.5/bin/python"
    - "bin/pip install coveralls"
script: "travis_wait 40 make travis"
after_success: "bin/coveralls"
